name: Build and release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Determine release tag
        run: |
          echo "RELEASE_TAG=$(git log -1 --pretty='format:%cd' --date=format:'v%Y%m%d.%H%M%S')" >> "$GITHUB_ENV"
      - name: Build PDF
        # If it's not run twice (the first time to get the aux file) then the margin tick marks are not in the right place
        run: |
          docker run --rm -v $PWD:/workdir texlive/texlive:TL2022-historic bash -c "cd /workdir && pdflatex main.tex && bibtex main && pdflatex main.tex && pdflatex main.tex && mv main.pdf michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}.pdf"
      - name: Build PNG of first page
        run: |
          sudo apt-get install -y ghostscript
          gs -r600 -sDEVICE=png16m -o michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}.png michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}.pdf
      - name: Upload PDF and PNG
        uses: actions/upload-artifact@v3
        with:
          name: michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}
          path: |
            michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}.pdf
            michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}.png

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Determine release tag
        run: |
          echo "RELEASE_TAG=$(git log -1 --pretty='format:%cd' --date=format:'v%Y%m%d.%H%M%S')" >> "$GITHUB_ENV"
      - name: Download PDF and PNG
        uses: actions/download-artifact@v3
        with:
          name: michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}
          path: michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}
      - name: Create assets without the tag in their names (for /latest redirects)
        run: |
          cp michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}/michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}.pdf michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}/michal-charemza-openttd-msc-dissertation.pdf
          cp michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}/michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}.png michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}/michal-charemza-openttd-msc-dissertation.png
      - name: Create release tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.RELEASE_TAG }}',
              sha: context.sha
            })
      - name: Release PDF and PNG under release tag
        uses: softprops/action-gh-release@v1
        with:
          files: |
            michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}/michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}.pdf
            michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}/michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}.png
            michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}/michal-charemza-openttd-msc-dissertation.pdf
            michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}/michal-charemza-openttd-msc-dissertation.png
          generate_release_notes: true
          name: ${{ env.RELEASE_TAG }}
          body: |
            **First page** (click to download PDF of all pages):
            <a href="https://github.com/michalc/openttd-msc-dissertation/releases/download/${{ env.RELEASE_TAG }}/michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}.pdf">
              <img src="https://github.com/michalc/openttd-msc-dissertation/releases/download/${{ env.RELEASE_TAG }}/michal-charemza-openttd-msc-dissertation-${{ env.RELEASE_TAG }}.png" width="510">
            </a>
          tag_name: refs/tags/${{ env.RELEASE_TAG }}
