name: Build and release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Determine release tag
        run: |
          echo "RELEASE_TAG=$(git log -1 --pretty='format:%cd' --date=format:'v%Y%m%d.%H%M%S')" >> "$GITHUB_ENV"
      - name: Download and build Docker image
        run: |
          docker build . -t texlive-with-inkscape
      - name: Build PDF
        # If it's not run twice (the first time to get the aux file) then the margin tick marks are not in the right place
        run: |
          docker run --rm -v $PWD:/workdir texlive-with-inkscape bash -c "cd /workdir && pdflatex --shell-escape main.tex && bibtex main && pdflatex --shell-escape main.tex && pdflatex --shell-escape main.tex && mv main.pdf michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}.pdf"
      - name: Build PNG of pages
        run: |
          sudo apt update
          sudo apt-get install -y ghostscript
          gs -r150 -sDEVICE=png16m -o michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}-%03d.png michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}.pdf
          cat /etc/ImageMagick-6/policy.xml
          echo '<policymap></policymap>' | sudo tee /etc/ImageMagick-6/policy.xml
          montage -mode concatenate -geometry +0+0 michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}-*.png michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}.png
      - name: Generate project materials archive
        run:
          ./project/generate.sh
      - name: Upload PDF, PNG, and project materials
        uses: actions/upload-artifact@v3
        with:
          name: michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}
          path: |
            michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}.pdf
            michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}.png
            project.tgz

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Determine release tag
        run: |
          echo "RELEASE_TAG=$(git log -1 --pretty='format:%cd' --date=format:'v%Y%m%d.%H%M%S')" >> "$GITHUB_ENV"
      - name: Download PDF, PNG, and project materials
        uses: actions/download-artifact@v3
        with:
          name: michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}
          path: michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}
      - name: Create assets without the tag in their names (for /latest redirects)
        run: |
          cp michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}/michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}.pdf michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}/michal-charemza-openttdlab-msc-dissertation.pdf
          cp michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}/michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}.png michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}/michal-charemza-openttdlab-msc-dissertation.png
      - name: Find MD5 of project materials
        run: |
          PROJECT_MATERIALIS_MD5=$(md5 michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}/project.tgz | cut -d ' ' -f 1)
          echo "PROJECT_MATERIALIS_MD5=$PROJECT_MATERIALIS_MD5"
          echo "PROJECT_MATERIALIS_MD5=$PROJECT_MATERIALIS_MD5" >> "$GITHUB_ENV"
      - name: Move project materials file to have MD5-specific name
        run: |
          mv michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}/project.tgz michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}/project-${{ env.PROJECT_MATERIALIS_MD5 }}.tgz
      - name: Create release tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.RELEASE_TAG }}',
              sha: context.sha
            })
      - name: Release PDF, PNG, and project materials under release tag
        uses: softprops/action-gh-release@v1
        with:
          files: |
            michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}/michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}.pdf
            michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}/michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}.png
            michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}/michal-charemza-openttdlab-msc-dissertation.pdf
            michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}/michal-charemza-openttdlab-msc-dissertation.png
            michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}/project-${{ env.PROJECT_MATERIALIS_MD5 }}.tgz
          generate_release_notes: true
          name: ${{ env.RELEASE_TAG }}
          body: |
            **Montage of all pages** (click to download PDF):
            <a href="https://github.com/michalc/OpenTTDLab-MSc-Dissertation/releases/download/${{ env.RELEASE_TAG }}/michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}.pdf">
              <img src="https://github.com/michalc/OpenTTDLab-MSc-Dissertation/releases/download/${{ env.RELEASE_TAG }}/michal-charemza-openttdlab-msc-dissertation-${{ env.RELEASE_TAG }}.png">
            </a>
          tag_name: refs/tags/${{ env.RELEASE_TAG }}
